# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Phi3Assistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Phi3Assistant
  pod 'onnxruntime-objc', '~> 1.18.0'

  target 'Phi3AssistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Phi3AssistantUITests' do
    # Pods for testing
  end

end
